const ENGINEER = [
    "Software Engineer",
    "Mechanical Engineer",
    "Electrical Engineer",
    "Civil Engineer",
    "Aerospace Engineer",
    "Chemical Engineer",
    "Biomedical Engineer",
    "Environmental Engineer",
    "Industrial Engineer",
    "Nuclear Engineer",
    "Petroleum Engineer",
    "Structural Engineer",
    "Systems Engineer",
    "Automotive Engineer",
    "Computer Hardware Engineer",
    "Marine Engineer",
    "Robotics Engineer",
    "Mining Engineer",
    "Geotechnical Engineer",
    "Materials Engineer",
    "Agricultural Engineer",
    "Manufacturing Engineer",
    "Process Engineer",
    "Quality Engineer",
    "Reliability Engineer",
    "Safety Engineer",
    "Test Engineer",
    "Validation Engineer",
    "Network Engineer",
    "Field Engineer",
    "Project Engineer",
    "Design Engineer",
    "Firmware Engineer",
    "Embedded Systems Engineer",
    "Optical Engineer",
    "Photonics Engineer",
    "Instrumentation Engineer",
    "Telecommunications Engineer",
    "Power Engineer",
    "Control Systems Engineer",
    "Mechatronics Engineer",
    "Plastics Engineer",
    "Acoustic Engineer",
    "Railway Engineer",
    "Marine Systems Engineer",
    "HVAC Engineer",
    "Bioprocess Engineer",
    "Ceramics Engineer",
    "Drafting Engineer",
    "Metallurgical Engineer",
    "Production Engineer",
    "Logistics Engineer",
    "Packaging Engineer",
    "Piping Engineer",
    "Structural Design Engineer",
    "Survey Engineer",
    "Urban Planning Engineer",
    "Textile Engineer",
    "Water Resources Engineer",
    "Ocean Engineer",
    "Photonics Systems Engineer",
    "Software Development Engineer",
    "Automation Engineer",
    "VLSI Design Engineer",
    "Computer Vision Engineer",
    "Artificial Intelligence Engineer",
    "Machine Learning Engineer",
    "Data Engineer",
    "Big Data Engineer",
    "Cybersecurity Engineer",
    "DevOps Engineer",
    "Cloud Engineer",
    "Front-End Engineer",
    "Back-End Engineer",
    "Full Stack Engineer",
    "Mobile Applications Engineer",
    "Game Development Engineer",
    "Virtual Reality Engineer",
    "Augmented Reality Engineer",
    "Microelectronics Engineer",
    "Nanotechnology Engineer",
    "EHS Engineer",
    "Building Services Engineer",
    "Geothermal Engineer",
    "Wind Energy Engineer",
    "Solar Energy Engineer",
    "Hydropower Engineer",
    "Battery Engineer",
    "Fuel Cell Engineer",
    "Quantum Engineer",
    "Satellite Systems Engineer",
    "Railway Signaling Engineer",
    "Smart Grid Engineer",
    "Instrumentation and Control Engineer",
    "Wireless Communications Engineer",
    "RF Engineer",
    "EDA Engineer",
    "Medical Device Engineer",
    "NDT Engineer",
    "Project Controls Engineer",
    "Traffic Engineer",
    "Pipeline Engineer",
    "Plant Engineer",
    "Platform Engineer",
    "Plumbing Engineer",
    "Powertrain Engineer",
    "Principal Engineer",
    "Product Development Engineer",
    "Propulsion Engineer",
    "Quality Assurance Engineer",
    "Radiation Protection Engineer",
    "Rapid Prototyping Engineer",
    "Reactor Engineer",
    "Renewable Energy Engineer",
    "Research and Development Engineer",
    "Satellite Engineer",
    "SCADA Engineer",
    "Security Engineer",
    "Semiconductor Engineer",
    "Service Engineer",
    "Simulation Engineer",
    "Site Engineer",
    "Solid Waste Engineer",
    "Spacecraft Engineer",
    "Substation Engineer",
    "Supply Chain Engineer",
    "Surveying Engineer",
    "Sustainability Engineer",
    "Technical Support Engineer",
    "Tooling Engineer",
    "Transmission Engineer",
    "Transportation Engineer",
    "Vehicle Dynamics Engineer",
    "Virtualization Engineer",
    "Wastewater Engineer",
    "Water Treatment Engineer",
    "Web Engineer",
    "Wireless Engineer",
    "Welding Engineer",
    "Thermal Engineer",
    "Bridge Engineer",
    "Tunnel Engineer",
    "Rail Systems Engineer",
    "Explosives Engineer",
    "Sensor Engineer",
    "Seismic Engineer",
    "Petrochemical Engineer",
    "Plant Safety Engineer",
    "Machinery Engineer",
    "Medical Imaging Engineer",
    "Coastal Engineer",
    "Dredging Engineer",
    "Aquatic Engineer",
    "Hydraulic Engineer",
    "Industrial Design Engineer",
    "Infrastructure Engineer",
    "Pavement Engineer",
    "Construction Materials Engineer",
    "Remediation Engineer",
    "Geophysical Engineer",
    "Oilfield Engineer",
    "Refinery Engineer",
    "Marine Construction Engineer",
    "Well Engineer",
    "Downhole Engineer",
    "Rig Engineer",
    "Reservoir Engineer",
    "Drilling Engineer",
    "Production Logging Engineer",
    "Petroleum Production Engineer",
    "Subsea Engineer",
    "Completion Engineer",
    "Directional Drilling Engineer",
    "Measurement While Drilling (MWD) Engineer",
    "LWD Engineer",
    "Wireline Engineer",
    "Frac Engineer",
    "Stimulation Engineer",
    "Oil Sands Engineer",
    "Enhanced Oil Recovery (EOR) Engineer",
    "Hydrogen Engineer",
    "Pipeline Integrity Engineer",
    "Transportation Safety Engineer",
    "Environmental Safety Engineer",
    "Mining Safety Engineer",
    "Factory Safety Engineer",
    "Cybersecurity Network Engineer",
    "AI Software Engineer",
    "Deep Learning Engineer",
    "Algorithm Engineer",
    "Analytics Engineer",
    "Applied Mechanics Engineer",
    "Architectural Engineer",
    "Audio Engineer",
    "Automation Controls Engineer",
    "Automotive Design Engineer",
    "Aviation Engineer",
    "Biochemical Engineer",
    "Bioinformatics Engineer",
    "Broadcast Engineer",
    "CAD Engineer",
    "CNC Engineer",
    "Communications Engineer",
    "Composite Materials Engineer",
    "Computer Systems Engineer",
    "Configuration Engineer",
    "Construction Engineer",
    "Cryogenic Engineer",
    "Customer Support Engineer",
    "Data Center Engineer",
    "Demand Forecasting Engineer",
    "Digital Signal Processing (DSP) Engineer",
    "Drivetrain Engineer",
    "E-commerce Engineer",
    "Embedded Software Engineer",
    "Energy Engineer",
    "Enterprise Engineer",
    "Farming Equipment Engineer",
    "Flight Test Engineer",
    "Fluid Dynamics Engineer",
    "Formulation Engineer",
    "Foundry Engineer",
    "Freight Engineer",
    "Geodetic Engineer",
    "Global Positioning System (GPS) Engineer",
    "Graphics Engineer",
    "Green Energy Engineer",
    "Hardware Design Engineer",
    "Hazard Analysis Engineer",
    "Heat Transfer Engineer",
    "Highway Engineer",
    "Human Factors Engineer",
    "HVDC Engineer",
    "Information Systems Engineer",
    "Inspection Engineer",
    "Integration Engineer",
    "Intelligent Transportation Systems Engineer",
    "Interconnection Engineer",
    "Internet of Things (IoT) Engineer",
    "Land Development Engineer",
    "Landing Gear Engineer",
    "Lighting Engineer",
    "Lithography Engineer",
    "Maintenance Engineer",
    "Marine Propulsion Engineer",
    "Mass Transit Engineer",
    "Materials Handling Engineer",
    "Mechanical Design Engineer",
    "Mechanical Systems Engineer",
    "Medical Equipment Engineer",
    "Metrology Engineer",
    "Microwave Engineer",
    "Mining Equipment Engineer",
    "Molding Engineer",
    "Motor Design Engineer",
    "Nanomaterials Engineer",
    "Naval Architect",
    "Neural Network Engineer",
    "Nondestructive Testing (NDT) Engineer",
    "Nuclear Safety Engineer",
    "Operations Engineer",
    "Packaging Design Engineer",
    "Paleontology Engineer",
    "Pattern Recognition Engineer",
    "Performance Engineer",
    "Photovoltaic Engineer",
    "Pipeline Design Engineer",
    "Plasma Engineer",
    "Port Engineer",
    "Power Electronics Engineer",
    "Predictive Maintenance Engineer",
    "Public Works Engineer",
    "Quantum Computing Engineer",
    "Radar Engineer",
    "Radio Frequency Identification (RFID) Engineer",
    "Railway Construction Engineer",
    "Reservoir Simulation Engineer",
    "Resilience Engineer",
    "Resource Engineer",
    "Rolling Stock Engineer",
    "Rotor Dynamics Engineer",
    "Satellite Communications Engineer",
    "SCADA Systems Engineer",
    "Sealing Engineer",
    "Signal Processing Engineer",
    "Silicon Photonics Engineer",
    "Smart Building Engineer",
    "Solid State Engineer",
    "Space Systems Engineer",
    "Structural Dynamics Engineer",
    "Surface Engineer",
    "Sustainability Design Engineer"
]